apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "http-dragonfly.fullname" . }}-config
  labels:
    {{- include "http-dragonfly.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.config | indent 4 }}
