{{- range .Values.createConfigMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name | default (printf "%s-%s" (include "http-dragonfly.fullname" $) .folder) }}
  labels:
    {{- include "http-dragonfly.labels" $ | nindent 4 }}
data:
{{ ($.Files.Glob (printf "%s/*" .folder)).AsConfig | indent 2 }}
{{- end }}
