apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clustergitrepos.git-events-runner.rs
spec:
  group: git-events-runner.rs
  names:
    categories: []
    kind: ClusterGitRepo
    plural: clustergitrepos
    shortNames: []
    singular: clustergitrepo
  scope: Cluster
  versions:
    - additionalPrinterColumns: []
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: ClusterGitRepo custom resource definition
          properties:
            spec:
              description: ClusterGitRepo CRD spec section
              properties:
                authConfig:
                  description: Auth config section
                  nullable: true
                  properties:
                    keys:
                      default:
                        password: password
                        privateKey: ssh-privatekey
                        token: token
                        username: username
                      description: Keys in the secret data section for different auth parameters
                      properties:
                        password:
                          type: string
                        privateKey:
                          type: string
                        token:
                          type: string
                        username:
                          type: string
                      required:
                        - password
                        - privateKey
                        - token
                        - username
                      type: object
                    secretRef:
                      description: Reference to the secret
                      properties:
                        name:
                          type: string
                        namespace:
                          nullable: true
                          type: string
                      required:
                        - name
                      type: object
                    type:
                      description: Repos' type of the authentication
                      enum:
                        - basic
                        - token
                        - ssh
                      type: string
                  required:
                    - secretRef
                    - type
                  type: object
                repoUri:
                  description: Full URI of the repo
                  pattern: ^git@[\w.-]+:[\w.-]+/[/\w.-]+$|^ssh://([\w.-]+@)?[\w.-]+(:[\d]{1,5})?(/([/\w.-]+)?)?$|^https?://[\w.-]+(:[\d]{1,5})?(/([/%&=\?\w.-]+)?)?$
                  type: string
                tlsConfig:
                  description: TLS config section
                  nullable: true
                  properties:
                    caCert:
                      description: Repo custom TLS CA config
                      nullable: true
                      properties:
                        key:
                          default: ca.crt
                          type: string
                        secretRef:
                          description: Reference to the secret
                          properties:
                            name:
                              type: string
                            namespace:
                              nullable: true
                              type: string
                          required:
                            - name
                          type: object
                      required:
                        - secretRef
                      type: object
                    noVerifySsl:
                      default: false
                      type: boolean
                  type: object
              required:
                - repoUri
              type: object
          required:
            - spec
          title: ClusterGitRepo
          type: object
      served: true
      storage: true
      subresources: {}
