apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scheduletriggers.git-events-runner.rs
spec:
  group: git-events-runner.rs
  names:
    categories: []
    kind: ScheduleTrigger
    plural: scheduletriggers
    shortNames: []
    singular: scheduletrigger
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: current trigger state
          jsonPath: .status.state
          name: State
          type: string
        - description: time of last trigger run
          format: date-time
          jsonPath: .status.lastRun
          name: Last Run
          type: date
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: ScheduleTrigger custom resource definition
          properties:
            spec:
              description: Schedule trigger spec section
              properties:
                action:
                  description: Reference to the action to run from the trigger
                  properties:
                    kind:
                      description: Allowed action kinds
                      enum:
                        - Action
                        - ClusterAction
                      type: string
                    name:
                      type: string
                  required:
                    - kind
                    - name
                  type: object
                schedule:
                  description: Type of the schedule
                  oneOf:
                    - required:
                        - interval
                    - required:
                        - cron
                  properties:
                    cron:
                      description: Cron schedule
                      type: string
                    interval:
                      description: Interval type
                      type: string
                  type: object
                sources:
                  description: Kind and list of the triggers' sources
                  properties:
                    kind:
                      default: GitRepo
                      description: Allowed kinds of the sources
                      enum:
                        - GitRepo
                        - ClusterGitRepo
                      type: string
                    names:
                      items:
                        type: string
                      type: array
                    watchOn:
                      default:
                        onChangeOnly: true
                        reference:
                          branch: main
                      description: Trigger watching config
                      properties:
                        files:
                          description: '`gitignore`-like files specification to calculate hash'
                          items:
                            type: string
                          nullable: true
                          type: array
                        onChangeOnly:
                          description: '`true`: run action if repo was changed only `false`: run action every time trigger fire'
                          type: boolean
                        reference:
                          default:
                            branch: main
                          description: Which reference should be checked?
                          oneOf:
                            - required:
                                - branch
                            - required:
                                - tag
                            - required:
                                - commit
                          properties:
                            branch:
                              description: Use branch
                              type: string
                            commit:
                              description: Use particular commit hash
                              type: string
                            tag:
                              description: Ise tag
                              type: string
                          type: object
                      required:
                        - onChangeOnly
                      type: object
                  required:
                    - names
                  type: object
              required:
                - action
                - schedule
                - sources
              type: object
            status:
              description: Trigger status section
              nullable: true
              properties:
                checkedSources:
                  additionalProperties:
                    description: Result of checking of each source in the trigger
                    properties:
                      changed:
                        description: Timestamp of the last change of the source content
                        nullable: true
                        type: string
                      commitHash:
                        description: Last verified commit
                        nullable: true
                        type: string
                      fileHash:
                        description: Last verified has of the files (if present0)
                        nullable: true
                        type: string
                    type: object
                  description: Result of each source run
                  type: object
                lastRun:
                  description: Timestamp of the last run
                  nullable: true
                  type: string
                state:
                  description: 'State: idle, running, ...'
                  enum:
                    - Idle
                    - Running
                    - WrongConfig
                  type: string
              required:
                - checkedSources
                - state
              type: object
          required:
            - spec
          title: ScheduleTrigger
          type: object
      served: true
      storage: true
      subresources:
        status: {}
