apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "git-events-runner.configMapName" . }}
  namespace: {{ .Values.controllerNamespace | default .Release.Namespace }}
  labels:
    {{- include "git-events-runner.labels" . | nindent 4 }}
data:
  runtimeConfig: |
{{ tpl (toYaml .Values.runtimeConfig) . | indent 4 }}
