apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "git-events-runner.fullname" . }}
  namespace: {{ .Values.controllerNamespace | default .Release.Namespace }}
  labels:
    {{- include "git-events-runner.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "git-events-runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.prometheus.pdoAnnotations }}
        prometheus.io/port: {{ .Values.service.utility.port | quote }}
        prometheus.io/scheme: http
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "git-events-runner.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "git-events-runner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - run
            - --webhooks-port
            - {{ .Values.service.webhook.port | default 8080 | quote }}
            - --utility-port
            - {{ .Values.service.utility.port | default 3000 | quote }}
            - --schedule-parallelism
            - {{ .Values.service.scheduleParallelism | default 16 | quote }}
            - --webhooks-parallelism
            - {{ .Values.service.webhooksParallelism | default 16 | quote }}
            - --secrets-cache-time
            - {{ .Values.controllerOptions.secretsCacheTime | default 60 | quote }}
            - --source-clone-folder
            - {{ .Values.controllerOptions.sourceCloneFolder.mountPath | default "/tmp/git-events-runner" | quote }}
            - --config-map-name
            - {{ include "git-events-runner.configMapName" . }}
            - --leader-lease-name
            - {{ include "git-events-runner.leaderLeaseName" . }}
            - --leader-lease-duration
            - {{ .Values.controllerOptions.leaderLease.duration | default 30 | quote }}
            - --leader-lease-grace
            - {{ .Values.controllerOptions.leaderLease.grace | default 5 | quote }}
            - --metrics-prefix
            - {{ .Values.controllerOptions.metricsPrefix | default "git_events_runner" | quote }}
            {{- if .Values.controllerOptions.webhooksRateLimits.global }}
            - --hooks-rrl-global
            - {{ .Values.controllerOptions.webhooksRateLimits.global | quote }}
            {{- end }}
            {{- if .Values.controllerOptions.webhooksRateLimits.trigger }}
            - --hooks-rrl-trigger
            - {{ .Values.controllerOptions.webhooksRateLimits.trigger | quote }}
            {{- end }}
            {{- if .Values.controllerOptions.webhooksRateLimits.source }}
            - --hooks-rrl-source
            - {{ .Values.controllerOptions.webhooksRateLimits.source | quote }}
            {{- end }}
            {{- if or .Values.controllerOptions.webhooksTls.certPath .Values.controllerOptions.webhooksTls.keyPath }}
            - --tls-cert-path
            - {{ .Values.controllerOptions.webhooksTls.certPath | quote }}
            - --tls-key-path
            - {{ .Values.controllerOptions.webhooksTls.keyPath | quote }}
            {{- end }}
            {{- if .Values.controllerOptions.webhooksTls.secretName }}
            - --tls-secret-name
            - {{ .Values.controllerOptions.webhooksTls.secretName | quote }}
            {{- end }}
            {{- if .Values.controllerOptions.webhooksTls.secretNamespace }}
            - --tls-secret-namespace
            - {{ .Values.controllerOptions.webhooksTls.secretNamespace | quote }}
            {{- end }}
          env:
            - name: RUST_LOG
              value: {{ .Values.controllerOptions.logLevel | default "info" | quote }}
            {{- if .Values.controllerOptions.otlp.enabled }}
            - name: OPENTELEMETRY_ENDPOINT_URL
              value: {{ .Values.controllerOptions.otlp.endpoint | quote }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: utility
              containerPort: {{ .Values.service.utility.port }}
              protocol: TCP
            - name: webhook
              containerPort: {{ .Values.service.webhook.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.controllerOptions.sourceCloneFolder }}
            - name: {{ .volumeName }}
              mountPath: {{ .mountPath }}
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- with .Values.controllerOptions.sourceCloneFolder }}
        - name: {{ .volumeName }}
          emptyDir: {}
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
