{{- if and .Values.controllerNamespace .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.controllerNamespace }}
  labels:
    {{- include "git-events-runner.labels" . | nindent 4 }}
{{- end }}
