name: Continuous integration
on: pull_request

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint helm charts
        run: |
          for c in `ls charts`; do
            helm lint charts/${c}
          done
